### ISSUE TITLE
Missing or unreadable config file isn't an error

### ISSUE THREAD

**Issue by nosborn** [nosborn/github-action-markdown-cli#3]
`markdownlint-cli` treats it as a warning condition not an error if `config_file` is specified but the file isn't found or can't be read. It feels as though this should probably be an error condition.

I'm considering explicitly checking in `entrypoint.sh` that `config_file` can be read. Not absolutely convinced about it though.

**Comment by nvtkaszpir** [comment]
This should be reported to markdownlint-cli project itself.
