### ISSUE TITLE
auto fix?

### ISSUE THREAD

**Issue by z3by** [nosborn/github-action-markdown-cli#7]
is there any way to enable auto-fix using this action?

**Comment by jamesgorrie** [comment]
@z3by did you have any luck with this?

**Comment by z3by** [comment]
check it out here how I managed to do it https://github.com/z3by/ahmadmostafa.com/tree/master/.github/workflows

**Comment by z3by** [comment]
You can install nodejs then the actual package `markdownlint` from npm
and run this command in your action 
`markdownlint '**/*.md' --ignore node_modules --fix`
